### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by noncomplete** [lmmentel/ase-espresso#10]
I'm trying to run calculations in Jupyter. Even when I import everything from espresso package, its still throwing TypeError. 

Am I doing something wrong here?

![Screenshot_2019-09-20_20-16-13](https://user-images.githubusercontent.com/42934637/65334093-9081de00-dbe3-11e9-853f-9c03024ec682.png)

**Comment by lmmentel** [comment]
Hi @noncomplete,

I think the problem is that you are trying to use module `espresso` instead of and instance of `Espresso` class (please note capitalized name). I would suggest trying 
```
from espresso import Espresso
...
calc = Espresso(...
```
FYI there is also some basic documentation here https://ase-espresso.readthedocs.io/en/latest/index.html
