### ISSUE TITLE
Expected  relaxed atoms to update the ase.atoms positions property

### ISSUE THREAD

**Issue by mklilley** [lmmentel/ase-espresso#11]
Hi.

Maybe I misunderstood the library, but I assumed that if I used QE in relax mode then at the end of the calculation the `atoms.positions` would update to be the new relaxed values. This doesn't appear to be the case.

When I dug into the code I found a [`read`](https://github.com/lmmentel/ase-espresso/blob/91e7dc7dd75db4ec98ac10f60e0ada995ae8b75e/espresso/espresso.py#L878) function that looks like it might be part of this, but when `positions` are calculated using `self.read_positions()` they don't get saved anywhere.

Related to [`read_positions()`](https://github.com/lmmentel/ase-espresso/blob/91e7dc7dd75db4ec98ac10f60e0ada995ae8b75e/espresso/espresso.py#L1854), when I run that function it also doesn't output the new atomic positions. When I look at [the code](https://github.com/lmmentel/ase-espresso/blob/91e7dc7dd75db4ec98ac10f60e0ada995ae8b75e/espresso/espresso.py#L1879) I find  `carteslinenos ` is being looped over rather than `crystallinenos` which is what I would expect.

I am still very new to QE in general so I hope my questions aren't totally stupid. If so, I appreciate your patience :-)

**Comment by lmmentel** [comment]
Hi sorry for taking so long to answer but I stopped using the library some time ago and don't have the time to actively maintain it. I don't remember how exactly the attributes are update since it's partially taken care of by ASE. As far as my experience was this was working fine and I got optimized structures out of it.
