### ISSUE TITLE
multiple calculators in the same script

### ISSUE THREAD

**Issue by zulissi** [lmmentel/ase-espresso#12]
Thanks for making this and cleaning up the ase-espresso scripts!

I think the assumption is that this is used in a single bash script for a single calculation. The log file goes to qe-"pid"/log. This is true even if you make multiple calculators for different atoms objects.

For example
`atoms = Atoms('CC')
calc = Espresso()
atoms.set_calculator(calc)
atoms.get_potential_energy()

atoms = Atoms('CCC')
calc = Espresso()
atoms.set_calculator(calc)
atoms.get_potential_energy()`

Will throw errors because the first atoms object has two atoms, the second has three, and they both append to the same log file which is being parsed to get the forces.

I forked the repo and added a uuid to the log file so that each new calculator gets its own log file (e.g. log-some-long-uuid). This works, but assumes that each calculator is associated with a single atoms object. The above code would work, but the below code would note.

`atoms = Atoms('CC')
calc = Espresso()
atoms.set_calculator(calc)
atoms.get_potential_energy()

atoms = Atoms('CCC')
atoms.set_calculator(calc) #previous calc is being reused
atoms.get_potential_energy()`

I'm not sure what the correct choice in this case is; maybe change the parser so that it only reads the last (most recent) log? Or maybe have a separate log for every QE invocation inside of the calculator (rather than appending)?

**Comment by lmmentel** [comment]
I would be happy to help but I have never tried to use Espresso in the way you're trying to do it. In order to provide some advice it would be great to see what problem are you tying to solve here. 

I've used the package int he past with multiple calculators for the same `Atoms` object in order to chain the computational steps but never stumbled upon the case of same you're describing.

One generic piece o advice is that all of the objects (`Atoms`, `Espresso` etc) are python object so the can be reused as such.

**Comment by zulissi** [comment]
Thanks! Yes, I understand the normal use case of running a single batch job with an atoms input and multiple calculators.

I came across this when helping with this:
https://kitchingroup.cheme.cmu.edu/dft-book-espresso/02-molecules.html

The document has multiple atoms objects in the same document, which causes the error described above.

That document should run in colab successfully. The dftbook package is basically just a wrapper around installing QE, GBRV pseudopotentials, and my fork of ase-espresso (with a one-line change to make the log file dynamic): https://github.com/ulissigroup/ase-espresso/commit/78aa9fc7845e22c4d49866f743ea562f90b9e400#diff-02b5b69595937260449e2486027f3af7

**Comment by lmmentel** [comment]
Thanks for the context, now it's clearer what the use case is. I don't know how deeply you looked into the code but there is  `SiteConfig` object for configuring the execution environment with a method for setting the `Espresso` into the interactive mode that might be a good fit for the notebook mode, see https://github.com/lmmentel/ase-espresso/blob/91e7dc7dd75db4ec98ac10f60e0ada995ae8b75e/espresso/siteconfig.py#L142
