### ISSUE TITLE
Issues with PBS 

### ISSUE THREAD

**Issue by sandipde** [lmmentel/ase-espresso#14]
Hello,
  I am trying to use this great imporived version of the code of yours with PBS. I solved the obvious error with missing two variable in siteconfig , set_pbs_env by  
self.nodelist=uniqnodes
self.nnodes=len(uniqnodes)
And it seems to work now. However, I am wondering how do I do the followign simple thing which I was able to do easily with the default ase calculator 
1. If I don't want to go via all the extra features of automatically setting PBS stuff but just want to set the espresso command , the way it is done in default calculator.
2. setting the desired name of pseudopotential files
3. How do I pass on input parameters like vdw_corr ? 

Thanks a lot in advance.

**Comment by lmmentel** [comment]
Thanks for reporting this, but I have a very limited capacity to support this project.

> 1. If I don't want to go via all the extra features of automatically setting PBS stuff but just want to set the espresso command , the way it is done in default calculator.

I don't exactly understand your use case but if you set `scheduler=None` in `SiteConfig` you should be able to execute expresso jobs without a scheduler.

>  2. setting the desired name of pseudopotential files

That is a configuration specific to your QE installation

> 3. How do I pass on input parameters like vdw_corr ?

I don't  know that specific parameter, have you tried QE docs?

**Comment by sandipde** [comment]
Hi @lmmentel regarding number 3. the vdw_corr is an input parameter for vanderwars correction ( https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm618 ). In ase-espresso there are no options to add any other input keywords which are not hardcoded in the code.

**Comment by lmmentel** [comment]
It seems that the current `ase-espresso` might be a bit behind the releases of QE and not all the keywords are available. If you want you could add that parameter to `Espresso.__init__` and update the relevant section in [write_input](https://github.com/lmmentel/ase-espresso/blob/91e7dc7dd75db4ec98ac10f60e0ada995ae8b75e/espresso/espresso.py#L1239). I'm happy to accept a PR with that update.

**Comment by sandipde** [comment]
Alright ! let me do that. thanks :-)
