### ISSUE TITLE
creation of siteconfig for parallel calculation with the SGE scheduler

### ISSUE THREAD

**Issue by maxfxam** [lmmentel/ase-espresso#6]
I am trying to run ASE/ESPRESSO/BEEF on a cluster with SGE scheduler(http://gridscheduler.sourceforge.net/htmlman/manuals.html). The QuantumEspresso (5.1.r11289-pybeef version)  installed there runs well for parallel calculation. But I am missing some information on how to configure the ase-espresso interface on clusters with SGE scheduler. It will be great if the SiteConfig can cover it.

**Comment by lmmentel** [comment]
I made a first draft of the SGE support in ``SiteConfig`` class. The changes are in the  [ll branch](https://github.com/lmmentel/ase-espresso/tree/ll). I do not have access to a cluster with SGE so it would be great if you could test the code and I'll merge it if it works.

Remember that currently SGE is not detected automatically by ``Espresso`` so to use SGE pass the ``site='SGE'`` to ``Espresso`` or ``iEspresso`` on initialization.
