### ISSUE TITLE
Correct way to supply SCRATCH name in the Espresso object?

### ISSUE THREAD

**Issue by RKBK** [lmmentel/ase-espresso#7]
Hi!
First of all, thanks for the great work in making ase-espresso much more easy to install and use.

I'm trying to run ase-espresso on a cluster where the SCRATCH flag is "SNIC_TMP". There is an easy way to supply an alternate scratch flag if you manually create a site config object. But how exactly should I supply that to an Espresso calculator?
Can I do something like
```
calc = Espresso(site={'scratchenv': 'SNIC_TMP'})
```
or do I need to supply an object? How exactly should I go about doing this?

**Comment by lmmentel** [comment]
Hi!

I'm glad you find the package useful.

You can pass a ``Site`` instance to ``Espresso`` directly, so the code would look something like

```python
from espresso import Espresso
from espresso.siteconfig import SiteConfig

calc = Espresso(site=SiteConfig('PBS', scratchenv='SNIC_TMP'))
```
if you're using PBS/TORQUE. The first argument of `Site` (`scheduler`) is positional and therefore needs to be supplied.

Hope that helps.

**Comment by RKBK** [comment]
That's very helpful. Thank you!

**Comment by mklilley** [comment]
Hi.

Thanks for making the library. I'm just experimenting at this stage so I'm using my mac. I'm having issues with the SRATCH variable though. I'm getting the error:

```
OSError: SHELL variable SCRATCH is undefied
```

When I type `print(os.getenv('LOCAL_SCRATCH'))` I get `None` so I understand where the error is coming from. I am confused though because when I was just using the `ase.calculators.espresso` I had no errors.

I'd really appreciate any help you could offer.

Thanks

**Comment by mklilley** [comment]
Hello again.

I decided to just specify a `SCRATCH` variable and see what happens - now it is getting stuck at `PBS_O_WORKDIR `. I sense it might think i'm trying to use a cluster perhaps? 

Thanks again

Matt

**Comment by mklilley** [comment]
Not sure what my mac is doing, but I managed to solve the problem by setting `site=SiteConfig()`

**Comment by lmmentel** [comment]
I'm glad you solved it. Generally the `SiteConfig()` is needed to configure the cluster environment for executing parallel jobs. Then you need to set env vars yourself in the execution env or pass them to `SiteConfig`. Hope that helps.
