### ISSUE TITLE
Handling SLURM clusters where $SUBMITDIR is not set

### ISSUE THREAD

**Issue by RKBK** [lmmentel/ase-espresso#8]
Hi,

on the SLURM cluster I use (the Swedish HPC2N supercomputing center at Umeå Univ), $SUBMITDIR Is not set. This causes trouble with this line:
https://github.com/lmmentel/ase-espresso/blob/master/espresso/siteconfig.py#L177

I realize it's pretty easy to set the environment variable e.g. in the input script but it is still a small inconvenience. Perhaps an alternative would be to set the current directory as SUBMITDIR?

(specifically one can avoid this problem by just setting (because one needs to navigate to the folder where the job is run to execute it)
```
export SUBMITDIR=$PWD
```
in the submission script on HPC2N)

**Comment by lmmentel** [comment]
Could you check if ``SLURM_SUBMIT_DIR`` is set instead?
