### ISSUE TITLE
Format for "Forces acting on atoms" changed in new QE, breaks ase-espresso

### ISSUE THREAD

**Issue by RKBK** [lmmentel/ase-espresso#9]
Hi,

In QE 6.1, the line preceding that of the per-atom forces reads
```
     Forces acting on atoms (cartesian axes, Ry/au):
```
rather than just without "cartesian axes," as is assumed in ase-espresso. This breaks ase-espresso. Perhaps it could just try to match on everything preceding `(certesian axes, Ry/au)`?

**Comment by lmmentel** [comment]
Thanks for spotting that.

Could you attach a example log from QE 6.1, that I could use to test?

**Comment by RKBK** [comment]
Here you go:

[log.txt](https://github.com/lmmentel/ase-espresso/files/1256819/log.txt)
